{
 "title": "Reblaze Threats Overview [v5]",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font size= \"10\"> <center>  Reblaze threats overview  </center></font> "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic Peak (5m)",
   "type": "table",
   "description": "total number of requests  ",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(sum(increase(hits_total[5m])))",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(increase(hits_total[5m])) " }
   ]
  },
  {
   "title": "Passed",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(passed_total[5m])))"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(     sum(increase(hits_total[5m])) -  sum(increase(passed_total[5m]))   -  sum(increase(reported_total[5m]))   )"
    }
   ]
  },
  {
   "title": "Report",
   "type": "stat",
   "description": "total number of requests  labeled as report ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(reported_total[5m])))"
    }
   ]
  },
  {
   "title": "bot",
   "type": "stat",
   "description": "total number of requests  labeled as bot ",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(increase(hits_total[5m]))" }
   ]
  },
  {
   "title": "Human",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(increase(human_total[5m]))" }
   ]
  },
  {
   "title": "Challenge",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(challenge_total[5m]))"
    }
   ]
  },
  {
   "title": "Traffic overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(increase(hits_total[5m]))", "legendFormat": "hits" },
    {
     "expr": "sum(increase(hits_total[5m])) - sum(increase(passed_total[5m]))  -  sum(increase(reported_total[5m]))",
     "legendFormat": "blocked"
    },
    {
     "expr": "sum(increase(passed_total[5m]))",
     "legendFormat": "passed"
    },
    {
     "expr": "sum(increase(reported_total[5m]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Traffic overview (ratio)",
   "type": "graph",
   "description": "Ratio of blocked,  passed, reported requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(hits_total[5m])) - sum(increase(passed_total[5m])) -  sum(increase(reported_total[5m])))",
     "legendFormat": "blocked"
    },
    {
     "expr": "round(sum(increase(passed_total[5m])))",
     "legendFormat": "passed"
    },
    {
     "expr": "round(sum(increase(reported_total[5m])))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (method) (increase(methods_total[5m]))",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "description": "total number of requests  grouped by http status",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (code) (increase(status_total[5m])) ",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Top Active Threats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (tag) (increase(top_rtc_active_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Reported Threats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (tag) (increase(top_rtc_reported_total[5m]))) ",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Top Active Tags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (tag) (increase(top_tags_active_total{tag!=\"rtc.*\"}[5m]))) ",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Top Reported Tags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (tag) (increase(top_tags_reported_total{tag!=\"rtc.*\"}[5m]))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique Arguments per request",
   "type": "graph",
   "description": "Number of  requests  per  unique  args  divided  into categories  (from 0 to 5, 6-10, 11-20,  greater then 21)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " round(sum by (group) (increase(top_max_args_per_request[5m]))) ",
     "legendFormat": "args:{{group}}"
    }
   ]
  },
  {
   "title": "Unique Headers per request",
   "type": "graph",
   "description": "Number of  requests  per  unique  Headers  divided  into categories  (from 0 to 5, 6-10, 11-20,  greater then 21)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (group) (increase(top_max_headers_per_request[5m]))) ",
     "legendFormat": "headers:{{group}}"
    }
   ]
  },
  {
   "title": "Unique Cookies per request",
   "type": "graph",
   "description": "Number of  requests  per  unique  Cookies  divided  into categories  (from 0 to 5, 6-10, 11-20,  greater then 21)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (group) (increase(top_max_cookies_per_request[5m]))) ",
     "legendFormat": "cookies:{{group}}"
    }
   ]
  },
  {
   "title": "Global Filter Blocked",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_globalfilter_active_total[5m]))",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Global Filter Reported",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_globalfilter_report_total[5m]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Rate Limit Blocked",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_ratelimit_active_total[5m]))",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Rate Limit Reported",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_ratelimit_report_total[5m]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "ACL active",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_acl_active_total[5m]))",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "ACL Reported",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_acl_report_total[5m]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Content Filter Blocked",
   "type": "stat",
   "description": "total number of requests  labeled  by  ruleid  (CF rule)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_cf_active_total[5m]))",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Content Filter  Reported",
   "type": "stat",
   "description": "total number of requests  labeled  by  ruleid  (CF rule)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_triggered_cf_report_total[5m]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Risk Level Blocked",
   "type": "gauge",
   "description": "number of requests grouped by risk level ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum by (level) (increase(risk_level_active_total[5m])) ))",
     "legendFormat": "Risk Level Blocked : {{level}}"
    }
   ]
  },
  {
   "title": "Risk Level Reported",
   "type": "gauge",
   "description": "number of requests grouped by risk level ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum by (level) (increase(risk_level_report_total[5m])) ))",
     "legendFormat": "Risk Level Report : {{level}}"
    }
   ]
  },
  {
   "title": "Reblaze Signatures (CF)",
   "type": "timeseries",
   "description": "total number of requests  grouped by http status",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20,(sum by (ruleid) (increase(top_ruleid_active_total[5m])) ))",
     "legendFormat": "{{ruleid}}"
    }
   ]
  },
  {
   "title": "Requests Triggered by Access Control List (ACL)",
   "type": "timeseries",
   "description": "Requests  labeled by ACL",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (aclid) (increase(top_aclid_passed_total[5m])) ",
     "legendFormat": "passed: {{aclid}}"
    },
    {
     "expr": "sum by (aclid) (increase(top_aclid_active_total[5m])) ",
     "legendFormat": "active:{{aclid}}"
    }
   ]
  },
  {
   "title": "Blocked Sections",
   "type": "timeseries",
   "description": "Number of blocked  requests per HTTP requests section  (URI, args, attrs, body, headers )",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,(round(increase(section_active_total[5m]))))",
     "legendFormat": "active:{{section}}"
    },
    {
     "expr": "topk(10,(round(increase(section_passed_total[5m])) ))",
     "legendFormat": "passed:{{section}}"
    },
    {
     "expr": "topk(10,(round(increase(section_reported_total[5m])) ))",
     "legendFormat": "repot:{{section}}"
    }
   ]
  },
  {
   "title": "Maximum Arguments, Cookies, Headers ",
   "type": "timeseries",
   "description": "Number of requests per maximum number of cookies, headers, args.\nShows anomaly for requests with abnormal number cookies, headers, args. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,(round(sum by (group) (increase(top_max_args_per_request[5m]))) ))",
     "legendFormat": "args:{{group}}"
    },
    {
     "expr": "topk(10,(round(sum by (group) (increase(top_max_cookies_per_request[5m]))) ))",
     "legendFormat": "cookies:{{group}}"
    },
    {
     "expr": "topk(10,(round(sum by (group) (increase(top_max_headers_per_request[5m]))) ))",
     "legendFormat": "headers:{{group}}"
    }
   ]
  }
 ]
}