{
 "title": "Reblaze Traffic Overview [v5]",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font size= \"10\"> <center>  Reblaze traffic overview  </center></font> "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "hits",
   "type": "stat",
   "description": "total number of requests   total ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(hits_total[5m]))  "
    }
   ]
  },
  {
   "title": "2xx",
   "type": "gauge",
   "description": "total number of requests   total ",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sum(increase(status_classes_total{code_class='2'}[5m]))",
     "legendFormat": "{{code_class}}xx"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "gauge",
   "description": "total number of requests   total ",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sum(increase(status_classes_total{code_class='3'}[5m]))",
     "legendFormat": "{{code_class}}xx"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "gauge",
   "description": "total number of requests   total ",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sum(increase(status_classes_total{code_class='4'}[5m]))",
     "legendFormat": "{{code_class}}xx"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "gauge",
   "description": "total number of requests   total ",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sum(increase(status_classes_total{code_class='5'}[5m]))",
     "legendFormat": "{{code_class}}xx"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(increase(hits_total[5m])) ", "legendFormat": "hits" },
    {
     "expr": "sum(increase(hits_total[5m])) - sum(increase(passed_total[5m]))  -    sum(increase(reported_total[5m]))",
     "legendFormat": "blocked"
    },
    {
     "expr": "sum(increase(passed_total[5m]))",
     "legendFormat": "passed"
    },
    {
     "expr": " sum(increase(reported_total[5m]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " round(sum by (method) (increase(methods_total[5m]))) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "timeseries",
   "description": "total number of requests  grouped by http statuses",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (code) (increase(status_total[5m])) ",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "type": "text",
   "description": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "<font size= \"4\"> <center>  Top Organisations, Countries  </center></font> "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Organisations (ASN) Passed",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(30,((sum by (asn) (increase(top_asn_passed_total[5m])))))",
     "legendFormat": "passed: {{asn}}"
    }
   ]
  },
  {
   "title": "Top Countries Passed",
   "type": "timeseries",
   "description": "number of  requests per country ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20,(round((sum by (country) (increase(top_country_passed_total[5m]))) )))",
     "legendFormat": "passed: {{country}}"
    }
   ]
  },
  {
   "title": "Top Organisations (ASN) Blocked",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(30,(sum by (asn) (increase(top_asn_active_total[5m]))))",
     "legendFormat": "blocked: {{asn}}"
    }
   ]
  },
  {
   "title": "Top Countries Blocked",
   "type": "timeseries",
   "description": "number of  requests per country ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(round(sum by (country) (increase(top_country_active_total[5m]))))",
     "legendFormat": "blocked: {{country}}"
    }
   ]
  },
  {
   "title": "Top Organisations (ASN) Reported",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,((sum by (asn) (increase(top_asn_reported_total[5m])))))",
     "legendFormat": "report: {{asn}}"
    }
   ]
  },
  {
   "title": "Top Countries Reported",
   "type": "timeseries",
   "description": "number of  requests per country  reported",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,(round((sum by (country) (increase(top_country_reported_total[5m]))))))",
     "legendFormat": "report: {{country}}"
    }
   ]
  },
  {
   "type": "text",
   "description": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
   "options": {
    "content": "<font size= \"4\"> <center>  Unique metrics  </center></font> "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unique Sessions ",
   "type": "timeseries",
   "description": "number of unique sessions",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum((unique_session_passed))) + round(sum(unique_session_active)) + round(sum((unique_session_reported))) ",
     "legendFormat": "unique sessions total"
    },
    {
     "expr": "round(sum((unique_session_passed))) ",
     "legendFormat": "unique sessions passed"
    },
    {
     "expr": "round(sum(unique_session_active)) ",
     "legendFormat": "unique sessions blocked"
    },
    {
     "expr": "round(sum((unique_session_reported))) ",
     "legendFormat": "unique session reported"
    }
   ]
  },
  {
   "title": "Unique URIs ",
   "type": "timeseries",
   "description": "number of unique sessions",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum((unique_uri_passed))) + round(sum(unique_uri_active)) + round(sum((unique_uri_reported))) ",
     "legendFormat": "unique URIs total"
    },
    {
     "expr": "round(sum((unique_uri_passed))) ",
     "legendFormat": "unique URIs passed"
    },
    { "expr": "round(sum(unique_uri_active))", "legendFormat": "unique URIs blocked" },
    {
     "expr": "round(sum((unique_session_reported))) ",
     "legendFormat": "unique URIs reported"
    }
   ]
  },
  {
   "title": "Unique Countries ",
   "type": "timeseries",
   "description": "number of unique sessions",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum((unique_country_passed))) + round(sum(unique_country_active))  + round(sum((unique_country_reported))) ",
     "legendFormat": "unique country total"
    },
    {
     "expr": "round(sum((unique_country_passed))) ",
     "legendFormat": "unique sessions passed"
    },
    {
     "expr": "round(sum(unique_country_active)) ",
     "legendFormat": "unique country blocked"
    },
    {
     "expr": "round(sum((unique_country_reported))) ",
     "legendFormat": "unique country reported"
    }
   ]
  },
  {
   "title": "Unique IPs ",
   "type": "timeseries",
   "description": "number of unique sessions",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum((unique_ip_passed))) + round(sum(unique_ip_active)) + round(sum((unique_ip_reported))) ",
     "legendFormat": "unique IPs total"
    },
    {
     "expr": "round(sum((unique_ip_passed))) ",
     "legendFormat": "unique IPs passed"
    },
    { "expr": "round(sum(unique_ip_active))", "legendFormat": "unique IPs blocked" },
    {
     "expr": "round(sum((unique_ip_reported))) ",
     "legendFormat": "unique IPs reported"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(processing_time_average) by (proxy)",
     "legendFormat": "processing time average"
    },
    {
     "expr": " sum(processing_time_max) by (proxy)",
     "legendFormat": "bytes sent max"
    },
    {
     "expr": "sum(processing_time_min) by (proxy)",
     "legendFormat": "processing time min"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(bytes_sent_average) by (proxy)",
     "legendFormat": "bytes sent average"
    },
    {
     "expr": " sum(bytes_sent_max) by (proxy)",
     "legendFormat": "bytes sent max"
    },
    { "expr": "sum(bytes_sent_min) by (proxy)", "legendFormat": "bytes sent min" }
   ]
  },
  {
   "title": "Unique  User Agents ",
   "type": "timeseries",
   "description": "number of User Agents ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(30,(round(sum((unique_user_agent_passed))) + round(sum(unique_user_agent_active)) + round(sum((unique_user_agent_reported))) ))",
     "legendFormat": "unique User Agents total"
    },
    {
     "expr": "topk(30,(round(sum((unique_user_agent_passed)))))",
     "legendFormat": "unique User Agents  passed"
    },
    {
     "expr": "topk(30,(round(sum(unique_user_agent_active))))",
     "legendFormat": "unique User Agents blocked"
    },
    {
     "expr": "round(sum((unique_user_agent_reported))) ",
     "legendFormat": "unique User Agents  reported"
    }
   ]
  }
 ]
}